---
- name: Build Lustre RPMS
  hosts: localhost # Or your target build machine, e.g., 'buildservers'
  connection: local # If hosts is localhost. Remove if targeting remote build machine.
  gather_facts: true # Good to have facts, especially for ansible_os_family

  # vars:
    # Override any defaults from the role here if needed for testing
    # lustre_version: "2.15.3" # Example: Test a specific version
    # lustre_sign_rpms: true
    # lustre_rpm_gpg_key: "Your GPG Key ID For Testing"

  roles:
    - lustre_builder
