---
# tasks file for lustre_builder

- name: Ensure EPEL repository is enabled (RHEL family)
  ansible.builtin.package:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"
  become: true # KEEP

- name: Install Lustre build dependencies
  ansible.builtin.package:
    name:
      # Common dependencies
      - automake
      - bc
      - binutils-devel
      - bison
      - elfutils-devel
      - elfutils-libelf-devel
      - expect
      - flex
      - gcc
      - gcc-c++
      - git
      - glib2
      - glib2-devel
      - hmaccalc
      - krb5-devel
      - libattr-devel
      - libblkid-devel
      - libselinux-devel
      - libtool
      - libuuid-devel
      - libyaml-devel
      - lsscsi
      - make
      - ncurses-devel
      - net-snmp-devel
      - net-tools
      - patchutils
      - pciutils-devel
      - perl-ExtUtils-Embed
      - pesign
      - python3-devel
      - rpm-build
      - systemd-devel
      - tcl
      - tcl-devel
      - tk
      - tk-devel
      - wget
      - xmlto
      - asciidoc
      - zlib-devel
      - kernel-devel
      # RHEL/CentOS specific
      - redhat-rpm-config
      - yum-utils
    state: present
    update_cache: true
  become: true # KEEP
  vars:
    perl_extutils_pkg: "{{ 'perl-ExtUtils-MakeMaker' if ansible_os_family == 'RedHat' else 'perl-ExtUtils-Embed' }}"

- name: Ensure perl-ExtUtils-MakeMaker (for Embed) is installed on RHEL family
  ansible.builtin.package:
    name: "{{ perl_extutils_pkg }}"
    state: present
  become: true # KEEP (Matched name from existing file, prompt was slightly different but intent clear)
  when: ansible_os_family == "RedHat"

- name: Install kernel development package for SLES family
  ansible.builtin.package:
    name:
      - kernel-default-devel
    state: present
  when: ansible_os_family == "Suse"
  become: true # KEEP

- name: Ensure base source directory exists
  ansible.builtin.file:
    path: "{{ lustre_src_path }}"
    state: directory
    mode: '0755'
  # become: true # REMOVED as per instruction

- name: Clone Lustre source code repository
  ansible.builtin.git:
    repo: https://github.com/lustre/lustre-release.git
    dest: "{{ lustre_checkout_path }}"
    version: "{{ lustre_version }}"
    accept_hostkey: true
    force: true
  # become: true # REMOVED as per instruction

- name: Run autogen.sh for Lustre
  ansible.builtin.shell:
    cmd: sh autogen.sh
    chdir: "{{ lustre_checkout_path }}"
    creates: "{{ lustre_checkout_path }}/configure"
  # become: true # REMOVED as per instruction

- name: Run configure for Lustre
  ansible.builtin.command:
    cmd: ./configure --enable-server --enable-client
    chdir: "{{ lustre_checkout_path }}"
    creates: "{{ lustre_checkout_path }}/Makefile"
  # become: true # REMOVED as per instruction

- name: Build Lustre RPMs
  ansible.builtin.command:
    cmd: make rpms
    chdir: "{{ lustre_checkout_path }}"
  # become: true # REMOVED as per instruction

- name: Ensure RPM output directory exists
  ansible.builtin.file:
    path: "{{ lustre_version_rpm_path }}"
    state: directory
    mode: '0755'
  # become: true # REMOVED as per instruction

- name: Find generated RPMs
  ansible.builtin.find:
    paths: "{{ lustre_checkout_path }}"
    patterns: "*.rpm"
    recurse: yes
  register: found_rpms
  # become: true # REMOVED as per instruction

- name: Move compiled RPMs to destination directory
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "{{ lustre_version_rpm_path }}/"
    remote_src: true
    mode: '0644'
  loop: "{{ found_rpms.files }}"
  when: found_rpms.files | length > 0
  # become: true # REMOVED as per instruction

- name: Ensure rpm-sign package is installed (for signing)
  ansible.builtin.package:
    name: rpm-sign
    state: present
  when: lustre_sign_rpms | bool and lustre_rpm_gpg_key | length > 0
  become: true # KEEP

- name: Find RPMs in the versioned RPM path for signing
  ansible.builtin.find:
    paths:
      - "{{ lustre_version_rpm_path }}"
    patterns: "*.rpm"
  register: rpms_to_sign
  when: lustre_sign_rpms | bool and lustre_rpm_gpg_key | length > 0
  # become: true # REMOVED (was not present in previous version, confirmed removal)

- name: Sign Lustre RPMs
  community.general.rpm_sign:
    path: "{{ item.path }}"
    key_id: "{{ lustre_rpm_gpg_key }}"
  loop: "{{ rpms_to_sign.files }}"
  when:
    - lustre_sign_rpms | bool
    - lustre_rpm_gpg_key | length > 0
    - rpms_to_sign.files is defined
    - rpms_to_sign.files | length > 0
  # become: true # REMOVED as per instruction
